// File viewer e2e over the fake server. Run: bun run src/web/file-viewer.e2e.ts
import { chromium, type Page } from "playwright";
import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const PORT = Number(process.env.E2E_PORT) || 7552;
const BASE = `http://localhost:${PORT}`;
const PNG = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 0]);
const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

let pass = 0;
const fails: string[] = [];
async function step(name: string, fn: () => Promise<void>) {
  try {
    await fn();
    pass++;
    console.log(`  ✓ ${name}`);
  } catch (e: any) {
    fails.push(name);
    console.log(`  ✗ ${name} — ${String(e?.message ?? e).split("\n")[0]}`);
  }
}

async function waitReady() {
  for (let i = 0; i < 80; i++) {
    try {
      if ((await fetch(`${BASE}/api/state`)).ok) return;
    } catch {}
    await sleep(250);
  }
  throw new Error("server never became ready");
}

async function post(path: string, body: unknown) {
  const res = await fetch(`${BASE}${path}`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`${path} -> ${res.status}: ${await res.text()}`);
  return res;
}

async function openFilesConversation(page: Page) {
  await page.goto(BASE, { waitUntil: "domcontentloaded" });
  await page.locator('.mrow:has-text("files")').click();
  await page.locator('.conv-member-tab:has-text("codex-1")').click();
  await page.waitForSelector('.conv-control .sub:has-text("codex")', { timeout: 8000 });
}

const work = await mkdtemp(join(tmpdir(), "mesh-file-viewer-work-"));
await mkdir(join(work, "sub"));
await writeFile(join(work, "report.md"), "# Report\n\nThis is a linked report.\n\n![diagram](diagram.png)\n\n[server.ts](server.ts)\n");
await writeFile(join(work, "diagram.png"), PNG);
await writeFile(join(work, "server.ts"), "export const answer = 42;\n// generated by codex\n");
await writeFile(join(work, "secret.exe"), "classified");
await symlink(join(work, "server.ts"), join(work, "linked.ts"));

const server = Bun.spawn(["bun", "run", "src/main.ts", "--fake", "--port", String(PORT)], {
  stdout: "pipe",
  stderr: "pipe",
});
const browser = await chromium.launch({ headless: true });

try {
  await waitReady();
  await post("/api/meshes", {
    name: "files",
    agents: [
      { id: "router", harness: "claude", project: work, role: "router" },
      { id: "codex-1", harness: "codex", project: work, role: "member" },
    ],
    edges: [{ from: "router", to: "codex-1" }],
  });
  await post("/api/meshes/files/start", {});
  await post("/api/meshes/files/agents/codex-1/prompt", {
    text: "Links: [report.md](report.md) ![diagram](diagram.png) [server.ts](server.ts) [missing.md](missing.md)",
  });
  await sleep(700);

  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(String(e)));
  page.on("console", (m) => {
    if (m.type() === "error" && !/Failed to load resource/.test(m.text())) errors.push(m.text());
  });

  await step("desktop: transcript links open Markdown, code, and 404 viewer; inline image renders", async () => {
    await openFilesConversation(page);
    const agentBubble = page.locator(".msg.agent .bubble", { hasText: "Links:" }).last();
    await agentBubble.locator('img[src="/api/agents/codex-1/files/diagram.png"]').waitFor({ timeout: 8000 });

    await agentBubble.locator('a[href="/mesh/files/agent/codex-1/file/report.md"]').click();
    await page.waitForSelector(".file-viewer-path", { timeout: 8000 });
    await page.waitForSelector('.file-viewer-body h1:has-text("Report")', { timeout: 8000 });
    await page.waitForSelector('.file-viewer-body img[src="/api/agents/codex-1/files/diagram.png"]', { timeout: 8000 });
    await page.locator(".file-viewer-back").click();
    await page.waitForSelector(".conv-panel", { timeout: 8000 });

    await agentBubble.locator('a[href="/mesh/files/agent/codex-1/file/server.ts"]').click();
    await page.waitForSelector('.file-code:has-text("export const answer")', { timeout: 8000 });
    if ((await page.locator(".file-code .tok-keyword").count()) < 1) throw new Error("code did not render highlighted keyword spans");
    await page.locator(".file-viewer-back").click();
    await page.waitForSelector(".conv-panel", { timeout: 8000 });

    await agentBubble.locator('a[href="/mesh/files/agent/codex-1/file/missing.md"]').click();
    await page.waitForSelector('.file-viewer-error:has-text("File not found")', { timeout: 8000 });
    await page.locator(".file-viewer-back").click();
    await page.waitForSelector(".conv-panel", { timeout: 8000 });
  });

  await step("mobile: viewer has no horizontal overflow and back target is at least 44px", async () => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto(`${BASE}/mesh/files/agent/codex-1/file/report.md`, { waitUntil: "domcontentloaded" });
    await page.waitForSelector('.file-viewer-body h1:has-text("Report")', { timeout: 8000 });
    const scrollWidth = await page.evaluate(() => document.documentElement.scrollWidth);
    if (scrollWidth > 375) throw new Error(`page scrollWidth ${scrollWidth} > 375`);
    const box = await page.locator(".file-viewer-back").boundingBox();
    if (!box || box.width < 44 || box.height < 44) throw new Error(`bad back target ${JSON.stringify(box)}`);
    await page.waitForSelector('.file-viewer-body img[src="/api/agents/codex-1/files/diagram.png"]', { timeout: 8000 });
  });

  await step("negative API requests map traversal, non-whitelist, and symlink correctly", async () => {
    const traversal = await fetch(`${BASE}/api/agents/codex-1/files/..%2F..%2Fetc%2Fpasswd`);
    if (traversal.status !== 400) throw new Error(`traversal status ${traversal.status}`);
    const exe = await fetch(`${BASE}/api/agents/codex-1/files/secret.exe`);
    if (exe.status !== 404) throw new Error(`secret.exe status ${exe.status}`);
    const link = await fetch(`${BASE}/api/agents/codex-1/files/linked.ts`);
    if (link.status !== 400) throw new Error(`symlink status ${link.status}`);
  });

  await step("no page errors", async () => {
    if (errors.length) throw new Error(errors.slice(0, 3).join(" || "));
  });

  console.log(`\n  ${pass} passed, ${fails.length} failed`);
  if (fails.length) {
    console.log("  FAILED:", fails.join(", "));
    process.exitCode = 1;
  } else {
    console.log("  FILE VIEWER E2E OK");
  }
} finally {
  await browser.close();
  server.kill();
  await rm(work, { recursive: true, force: true });
}
